2024-02-29 12:14:31,479 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Configure stats pid to 26412
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240229_121431-moj3tawr\logs\debug.log
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240229_121431-moj3tawr\logs\debug-internal.log
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000204CA375630>
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:init():566] calling init triggers
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'batch_size': 128, 'n_units': 8}
2024-02-29 12:14:31,480 INFO    MainThread:26412 [wandb_init.py:init():591] re-initializing run, found existing run on stack: d5nzb7z3
2024-02-29 12:14:31,481 INFO    MainThread:26412 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_4hrs_mean/d5nzb7z3
2024-02-29 12:14:31,481 INFO    MainThread:26412 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-29 12:14:31,481 INFO    MainThread:26412 [wandb_run.py:_restore():2193] restore
2024-02-29 12:14:31,482 INFO    MainThread:26412 [wandb_run.py:_restore():2199] restore done
2024-02-29 12:14:36,840 INFO    MainThread:26412 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-29 12:14:36,840 INFO    MainThread:26412 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-29 12:14:36,844 INFO    MainThread:26412 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-29 12:14:36,902 INFO    MainThread:26412 [wandb_init.py:init():616] starting backend
2024-02-29 12:14:36,902 INFO    MainThread:26412 [wandb_init.py:init():620] setting up manager
2024-02-29 12:14:36,903 INFO    MainThread:26412 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 12:14:36,904 INFO    MainThread:26412 [wandb_init.py:init():628] backend started and connected
2024-02-29 12:14:36,906 INFO    MainThread:26412 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 12:14:36,906 INFO    MainThread:26412 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 12:14:36,906 INFO    MainThread:26412 [wandb_init.py:init():720] updated telemetry
2024-02-29 12:14:36,934 INFO    MainThread:26412 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 12:14:38,360 INFO    MainThread:26412 [wandb_run.py:_on_init():2262] communicating current version
2024-02-29 12:14:38,393 INFO    MainThread:26412 [wandb_run.py:_on_init():2271] got version response 
2024-02-29 12:14:38,393 INFO    MainThread:26412 [wandb_init.py:init():804] starting run threads in backend
2024-02-29 12:14:38,499 INFO    MainThread:26412 [wandb_run.py:_console_start():2241] atexit reg
2024-02-29 12:14:38,499 INFO    MainThread:26412 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-29 12:14:38,499 INFO    MainThread:26412 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-29 12:14:38,500 INFO    MainThread:26412 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-29 12:14:38,500 INFO    MainThread:26412 [wandb_init.py:init():847] run started, returning control to user process
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Configure stats pid to 26412
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:03:55,237 INFO    MainThread:26412 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:03:55,238 INFO    MainThread:26412 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240229_130355-vkvicadh\logs\debug.log
2024-02-29 13:03:55,238 INFO    MainThread:26412 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240229_130355-vkvicadh\logs\debug-internal.log
2024-02-29 13:03:55,238 INFO    MainThread:26412 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:03:55,238 INFO    MainThread:26412 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 128, 'n_units': 16}
2024-02-29 13:03:55,238 INFO    MainThread:26412 [wandb_init.py:init():591] re-initializing run, found existing run on stack: moj3tawr
2024-02-29 13:03:55,239 INFO    MainThread:26412 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_4hrs_mean/moj3tawr
2024-02-29 13:03:55,240 ERROR   MainThread:26412 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-02-29 13:03:55,240 INFO    MainThread:26412 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-29 13:03:55,240 INFO    MainThread:26412 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-29 13:03:55,240 INFO    MainThread:26412 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-29 13:03:55,240 INFO    MainThread:26412 [wandb_run.py:_restore():2193] restore
2024-02-29 13:03:55,240 INFO    MainThread:26412 [wandb_run.py:_restore():2199] restore done
2024-02-29 13:04:01,053 INFO    MainThread:26412 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-29 13:04:01,053 INFO    MainThread:26412 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-29 13:04:01,057 INFO    MainThread:26412 [wandb_run.py:_footer_sync_info():3825] logging synced files
