[W 2024-03-19 12:18:30,246] Trial 0 failed with parameters: {'batch_size': 64, 'n_units': 2, 'learning_rate': 5e-06, 'lr_decay': 0.85, 'lr_step': 10, 'negative_sampling': 2, 'loss': 'smooth_l1', 'update_freq': 4} because of the following error: RuntimeError('a Tensor with 0 elements cannot be converted to Scalar').
Traceback (most recent call last):
  File "c:\Users\CYP\anaconda3\envs\torch\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_24248\339626687.py", line 29, in objective
    auroc = train(batch_size,n_units,lr,lr_decay,lr_step,ns,loss,epochs,update_freq)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_24248\3389204729.py", line 13, in train
    sampler = CustomSampler(train_data,batch_size,ns=ns)
  File "c:\Users\CYP\Documents\GitHub\AIAKI\code\rl.py", line 173, in __init__
    self.indices = [i for i in range(len(data)) if data[i][2].item() == 0]
  File "c:\Users\CYP\Documents\GitHub\AIAKI\code\rl.py", line 173, in <listcomp>
    self.indices = [i for i in range(len(data)) if data[i][2].item() == 0]
RuntimeError: a Tensor with 0 elements cannot be converted to Scalar
[W 2024-03-19 12:18:30,247] Trial 0 failed with value None.
Exception ignored in: 'pyarrow._dataset._make_file_source'
Traceback (most recent call last):
  File "c:\Users\CYP\anaconda3\envs\torch\lib\site-packages\pyarrow\parquet\core.py", line 1340, in __init__
    fragment = parquet_format.make_fragment(single_file, filesystem)
