2024-03-19 05:05:43,393 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-19 05:05:43,393 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Configure stats pid to 23664
2024-03-19 05:05:43,393 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-03-19 05:05:43,393 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-03-19 05:05:43,393 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-19 05:05:43,394 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_050543-flj8yggo\logs\debug.log
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_050543-flj8yggo\logs\debug-internal.log
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_init.py:init():566] calling init triggers
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'n_units': 57, 'learning_rate': 0.0001, 'lr_decay': 0.6430934036559, 'lr_step': 20, 'ns': 10, 'loss': 'mse', 'update_freq': 126, 'PPO': 0, 'CQL': 0}
2024-03-19 05:05:43,396 INFO    MainThread:23664 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 6m0l443c
2024-03-19 05:05:43,397 INFO    MainThread:23664 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_Rescue_new/6m0l443c
2024-03-19 05:05:43,398 ERROR   MainThread:23664 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-19 05:05:43,398 INFO    MainThread:23664 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-19 05:05:43,398 INFO    MainThread:23664 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-19 05:05:43,398 INFO    MainThread:23664 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-19 05:05:43,398 INFO    MainThread:23664 [wandb_run.py:_restore():2193] restore
2024-03-19 05:05:43,398 INFO    MainThread:23664 [wandb_run.py:_restore():2199] restore done
2024-03-19 05:05:48,469 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-19 05:05:48,473 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-19 05:05:48,481 INFO    MainThread:23664 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-19 05:05:48,598 INFO    MainThread:23664 [wandb_init.py:init():616] starting backend
2024-03-19 05:05:48,599 INFO    MainThread:23664 [wandb_init.py:init():620] setting up manager
2024-03-19 05:05:48,601 INFO    MainThread:23664 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-19 05:05:48,602 INFO    MainThread:23664 [wandb_init.py:init():628] backend started and connected
2024-03-19 05:05:48,605 INFO    MainThread:23664 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-19 05:05:48,605 INFO    MainThread:23664 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-19 05:05:48,605 INFO    MainThread:23664 [wandb_init.py:init():720] updated telemetry
2024-03-19 05:05:48,628 INFO    MainThread:23664 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-19 05:05:50,014 INFO    MainThread:23664 [wandb_run.py:_on_init():2262] communicating current version
2024-03-19 05:05:50,045 INFO    MainThread:23664 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-19 05:05:50,045 INFO    MainThread:23664 [wandb_init.py:init():804] starting run threads in backend
2024-03-19 05:05:50,152 INFO    MainThread:23664 [wandb_run.py:_console_start():2241] atexit reg
2024-03-19 05:05:50,152 INFO    MainThread:23664 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-19 05:05:50,152 INFO    MainThread:23664 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-19 05:05:50,152 INFO    MainThread:23664 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-19 05:05:50,153 INFO    MainThread:23664 [wandb_init.py:init():847] run started, returning control to user process
2024-03-19 05:56:25,874 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-19 05:56:25,874 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Configure stats pid to 23664
2024-03-19 05:56:25,874 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-03-19 05:56:25,874 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-03-19 05:56:25,874 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_055625-6n4015we\logs\debug.log
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_055625-6n4015we\logs\debug-internal.log
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002030D3F3220>
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:init():566] calling init triggers
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'batch_size': 128, 'n_units': 18, 'learning_rate': 5e-05, 'lr_decay': 0.7949519347945544, 'lr_step': 14, 'ns': 5, 'loss': 'smooth_l1', 'update_freq': 128, 'PPO': 0, 'CQL': 0}
2024-03-19 05:56:25,875 INFO    MainThread:23664 [wandb_init.py:init():591] re-initializing run, found existing run on stack: flj8yggo
2024-03-19 05:56:25,876 INFO    MainThread:23664 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_Rescue_new/flj8yggo
2024-03-19 05:56:25,876 INFO    MainThread:23664 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-19 05:56:25,876 INFO    MainThread:23664 [wandb_run.py:_restore():2193] restore
2024-03-19 05:56:25,877 INFO    MainThread:23664 [wandb_run.py:_restore():2199] restore done
2024-03-19 05:56:30,587 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-19 05:56:30,591 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-19 05:56:30,603 INFO    MainThread:23664 [wandb_run.py:_footer_sync_info():3825] logging synced files
